apiVersion: v1
kind: Secret
metadata:
  name: tasksphere-secret
  namespace: tasksphere
type: Opaque
stringData:
  JWT_SECRET: change-me-in-production
  DATABASE_URL: postgresql://postgres:postgres@postgres.default.svc.cluster.local:5432/tasksphere?schema=public
